[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]
bytecode_hash = "none" # to get deterministic deployed code
solc = "0.8.17"

# GAS
gas_price = 110_000
gas_limit = 200_000_000
block_gas_limit = 10_000_000_000

# TESTS & OPTIMIZATION
fuzz_runs = 256
optimizer = true
optimizer_runs = 200

[profile.default.optimizer_details]
yul = false

[rpc_endpoints]
fevm = "${CALIBRATIONNET_RPC_URL}"
local = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config